import {chromium} from 'playwright';
import fs from 'node:fs/promises';
const b=await chromium.launch({channel:'chrome'});const p=await b.newPage({viewport:{width:1440,height:1000}});p.setDefaultTimeout(8000);
const pages=JSON.parse(await fs.readFile('reference/pages.json','utf8'));const content={};const extras=[];
for(const entry of pages){await p.goto(entry.url,{waitUntil:'domcontentloaded'});await p.waitForTimeout(300);content[entry.route]=await p.evaluate(()=>{
const txt=e=>e?.textContent?.trim()||'';
const rich=e=>{if(!e)return '';const clone=e.cloneNode(true);clone.querySelectorAll('script,style').forEach(n=>n.remove());clone.querySelectorAll('*').forEach(n=>{for(const a of [...n.attributes])if(!['href','colspan','rowspan'].includes(a.name))n.removeAttribute(a.name);if(!['P','BR','STRONG','B','EM','I','UL','OL','LI','H2','H3','H4','A','TABLE','THEAD','TBODY','TR','TH','TD'].includes(n.tagName))n.replaceWith(...n.childNodes)});return clone.innerHTML.trim()};
const root=document.querySelector('[data-elementor-type="wp-page"], [data-elementor-type="single-post"]');
const widget=e=>({kind:e.getAttribute('data-widget_type').split('.')[0],text:txt(e),html:rich(e.querySelector('.elementor-widget-container')),images:[...e.querySelectorAll('img')].map(i=>({src:i.src,srcset:i.srcset,alt:i.alt})),links:[...e.querySelectorAll('a[href]')].map(a=>({text:txt(a),url:a.href})),accordions:[...e.querySelectorAll('.elementor-toggle-item')].map(a=>({question:txt(a.querySelector('.elementor-toggle-title')),answer:rich(a.querySelector('.elementor-tab-content'))})),tabs:[...e.querySelectorAll('.elementor-tabs-content-wrapper > .elementor-tab-content')].map(a=>({id:a.getAttribute('data-tab'),html:rich(a)})),tabTitles:[...e.querySelectorAll('.elementor-tabs-wrapper > .elementor-tab-title')].map(txt)});
const sections=root?[...root.children].filter(s=>s.matches('section,.e-con')).map(s=>({headings:[...s.querySelectorAll('h1,h2,h3')].map(txt),widgets:[...s.querySelectorAll('.elementor-widget')].map(widget)})):[];
return {sections,article:rich(document.querySelector('.elementor-widget-theme-post-content')),title:txt(document.querySelector('h1')),forms:[...document.querySelectorAll('form')].map(f=>({fields:[...f.querySelectorAll('input,textarea,select')].map(e=>({type:e.type,label:e.placeholder,name:e.name,required:e.required,options:e.tagName==='SELECT'?[...e.options].map(o=>o.text):[]}))})),videoLinks:[...document.querySelectorAll('a[href*="lightbox"], [data-settings]')].map(e=>e.getAttribute('data-settings')||e.href).filter(v=>/video|mp4|youtube/.test(v))};});
for(const v of content[entry.route].videoLinks){try{const raw=v.startsWith('http')?JSON.parse(Buffer.from(new URLSearchParams(decodeURIComponent(new URL(v).hash.slice(1))).get('settings'),'base64').toString()):JSON.parse(v);if(raw.url)extras.push({originalUrl:raw.url,pages:[entry.url],methods:['video lightbox'],responsiveVariants:[]});}catch{}}
console.log('Content',entry.route);await fs.writeFile('reference/content.json',JSON.stringify(content,null,2));}
const assets=JSON.parse(await fs.readFile('reference/assets-discovered.json','utf8'));for(const a of extras)if(!assets.some(x=>x.originalUrl===a.originalUrl))assets.push(a);await fs.writeFile('reference/assets-discovered.json',JSON.stringify(assets,null,2));
await p.goto('https://tradekaro.com/',{waitUntil:'domcontentloaded'});await p.waitForTimeout(1500);await p.addStyleTag({content:'.zsiq_floatmain,.zsiq_theme1,.zsiq_chat_wrap,.zsiq-newtheme,.zsiq-mobhgt,.zsiq-float-tooltip,iframe[title*="chat"]{display:none!important}'});await fs.mkdir('reference/states',{recursive:true});
for(const name of ['Markets','Trading','Learn','About']){const nav=p.locator('.elementor-nav-menu--main').getByText(name,{exact:true}).filter({visible:true}).first();await nav.hover();await p.waitForTimeout(300);await p.screenshot({path:`reference/states/menu-${name.toLowerCase()}.png`});}
await p.mouse.move(0,0);const faq=p.locator('.elementor-tab-title').first();await faq.scrollIntoViewIfNeeded();await p.screenshot({path:'reference/states/faq-closed.png'});await faq.click();await p.waitForTimeout(350);await p.screenshot({path:'reference/states/faq-expanded.png'});
await p.setViewportSize({width:390,height:844});await p.goto('https://tradekaro.com/',{waitUntil:'domcontentloaded'});await p.waitForTimeout(1200);await p.addStyleTag({content:'[class*="zsiq"],#zsiqchat{display:none!important}'});await p.screenshot({path:'reference/states/mobile-hero-clean.png'});await p.locator('a[href*="popup"]').filter({visible:true}).first().click();await p.waitForTimeout(500);await p.screenshot({path:'reference/states/mobile-menu.png'});await p.getByText('Markets',{exact:true}).filter({visible:true}).first().click();await p.screenshot({path:'reference/states/mobile-menu-expanded.png'});
await b.close();
