import { chromium } from 'playwright';
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import sharp from 'sharp';
const root = path.resolve('reference');
const origin = 'https://tradekaro.com';
const mode = process.argv[2] || 'discover';
const browser = await chromium.launch({channel:'chrome', headless:true});
const context = await browser.newContext({viewport:{width:1440,height:1000},ignoreHTTPSErrors:true});
const page = await context.newPage();
const write = async (name,data) => {await fs.mkdir(path.dirname(path.join(root,name)),{recursive:true});await fs.writeFile(path.join(root,name),typeof data==='string'?data:JSON.stringify(data,null,2));};
const slug = url => new URL(url).pathname.replace(/^\/+|\/+$/g,'').replaceAll('/','--') || 'home';
const scroll = async p => {await p.evaluate(async()=>{for(let y=0;y<document.body.scrollHeight;y+=700){window.scrollTo(0,y);await new Promise(r=>setTimeout(r,60));}window.scrollTo(0,0);});await p.waitForTimeout(600);};
const assets = new Map();
function addAsset(url,source,method,variants=[]){if(!url||url.startsWith('data:'))return;try{url=new URL(url,source).href;}catch{return;}if(!/\.(svg|webp|png|jpe?g|avif|gif|woff2?|ttf|otf|mp4|webm|pdf)(\?|$)/i.test(url))return;const a=assets.get(url)||{originalUrl:url,pages:[],methods:[],responsiveVariants:[]};if(!a.pages.includes(source))a.pages.push(source);if(!a.methods.includes(method))a.methods.push(method);a.responsiveVariants=[...new Set([...a.responsiveVariants,...variants])];assets.set(url,a);}
page.on('response', response=>{if(['image','font','media'].includes(response.request().resourceType()))addAsset(response.url(),page.url(),response.request().resourceType());});
async function inspect(url){await page.goto(url,{waitUntil:'domcontentloaded',timeout:60000});await page.waitForTimeout(1500);await scroll(page);return await page.evaluate(()=>{
const visible = el=>el.getBoundingClientRect().width>0&&el.getBoundingClientRect().height>0;
const style = el=>{const s=getComputedStyle(el);const r=el.getBoundingClientRect();return {font:s.fontFamily,size:s.fontSize,weight:s.fontWeight,lineHeight:s.lineHeight,letterSpacing:s.letterSpacing,color:s.color,background:s.backgroundColor,backgroundImage:s.backgroundImage,padding:s.padding,margin:s.margin,gap:s.gap,radius:s.borderRadius,shadow:s.boxShadow,width:Math.round(r.width),height:Math.round(r.height),x:Math.round(r.x),y:Math.round(r.y+scrollY),display:s.display,direction:s.flexDirection,align:s.alignItems,justify:s.justifyContent};};
const links=[...document.querySelectorAll('a[href]')].map(a=>({url:a.href,text:a.innerText.trim(),area:a.closest('header')?'navbar':a.closest('footer')?'footer':'content'}));
const assetList=[];document.querySelectorAll('img,source,video,link[rel="preload"],a[href$=".pdf"]').forEach(el=>{const variants=(el.getAttribute('srcset')||el.getAttribute('data-srcset')||'').split(',').map(v=>v.trim().split(/\s+/)[0]).filter(Boolean);for(const url of [el.src,el.currentSrc,el.poster,el.getAttribute('data-src'),el.tagName==='LINK'||el.tagName==='A'?el.href:null,...variants])if(url)assetList.push({url,method:el.tagName,variants});});
document.querySelectorAll('*').forEach(el=>{for(const pseudo of [null,'::before','::after']){const s=getComputedStyle(el,pseudo);for(const m of s.backgroundImage.matchAll(/url\(["']?([^"')]+)["']?\)/g))assetList.push({url:m[1],method:pseudo?'CSS '+pseudo:'CSS background',variants:[]});}});
const widgets=[...document.querySelectorAll('.elementor-widget')].filter(el=>!el.closest('header,footer')).map(el=>({kind:el.getAttribute('data-widget_type'),text:el.innerText.trim(),images:[...el.querySelectorAll('img')].map(i=>({src:i.currentSrc||i.src,alt:i.alt,style:style(i)})),links:[...el.querySelectorAll('a[href]')].map(a=>({text:a.innerText,url:a.href})),style:style(el),children:[...el.querySelectorAll('h1,h2,h3,h4,p,.elementor-button,.elementor-icon-list-text')].slice(0,20).map(c=>({tag:c.tagName,text:c.innerText,style:style(c)}))}));
const sections=[...document.querySelectorAll('main > .elementor > section, .elementor[data-elementor-type="wp-page"] > section, .elementor[data-elementor-type="wp-page"] > .e-con, .elementor[data-elementor-type="single-post"] > section')].map(el=>({text:el.innerText,style:style(el),headings:[...el.querySelectorAll('h1,h2,h3,h4')].map(h=>h.innerText)}));
return {url:location.href,title:document.title,route:location.pathname,links,headings:[...document.querySelectorAll('h1,h2,h3,h4')].filter(visible).map(e=>({tag:e.tagName,text:e.innerText,style:style(e)})),interactiveElements:[...document.querySelectorAll('button,input,select,textarea,summary,[role="tab"],.elementor-tab-title')].filter(visible).map(e=>({tag:e.tagName,text:e.innerText,type:e.type,placeholder:e.placeholder})),widgets,sections,assets:assetList,bodyStyle:style(document.body),bodyText:document.body.innerText};});}
try {
if(mode==='discover'){
 const queue=[origin+'/'];const visited=new Set();const inventory=[];
 while(queue.length){const url=queue.shift();if(visited.has(url))continue;visited.add(url);try{console.log('Inspect',url);const data=await inspect(url);await write('inspection/'+slug(url)+'.json',data);inventory.push({url:data.url,title:data.title,route:data.route,navbarSection:url===origin+'/'?'Home':'Discovered public navigation',majorSections:data.sections.map(s=>s.headings),uniqueComponents:[...new Set(data.widgets.map(w=>w.kind))],visibleInteractiveElements:data.interactiveElements});for(const a of data.assets)addAsset(a.url,url,a.method,a.variants);for(const a of data.links){if(a.url.endsWith('.pdf'))addAsset(a.url,url,'legal document');const u=new URL(a.url);if(u.origin!==origin||u.hash||u.search||/\.(pdf|png|jpg|svg|zip|apk|exe)$/.test(u.pathname)||/wp-|feed|author\//.test(u.pathname))continue;const normalized=origin+u.pathname;if(!visited.has(normalized)&&!queue.includes(normalized))queue.push(normalized);}}catch(e){console.log('ERROR',url,e.message);inventory.push({url,error:e.message});}await write('pages.json',inventory);await write('assets-discovered.json',[...assets.values()]);}
 console.log('Pages discovered:',inventory.length,'Assets:',assets.size);
} else if(mode==='assets'){
 const found=JSON.parse(await fs.readFile(path.join(root,'assets-discovered.json'),'utf8'));const catalog=[];
 for(const a of found){try{const url=new URL(a.originalUrl);const ext=path.extname(url.pathname).toLowerCase();const category=/woff|ttf|otf/.test(ext)?'fonts':/mp4|webm/.test(ext)?'videos':ext==='.pdf'?'misc':/logo|trade-karo|tradekaro/i.test(url.pathname)?'logos':a.methods.some(m=>m.startsWith('CSS'))?'backgrounds':ext==='.svg'?'icons':'images';const filename=decodeURIComponent(path.basename(url.pathname)).replace(/[^a-zA-Z0-9._-]/g,'_');const local='assets/'+category+'/'+crypto.createHash('sha1').update(a.originalUrl).digest('hex').slice(0,8)+'-'+filename;let body;try{body=await fs.readFile(path.join(root,local));}catch{const response=await context.request.get(a.originalUrl,{timeout:45000});if(!response.ok())throw new Error('HTTP '+response.status());body=await response.body();await fs.mkdir(path.dirname(path.join(root,local)),{recursive:true});await fs.writeFile(path.join(root,local),body);}let dimensions=null;try{const meta=await sharp(body).metadata();dimensions={width:meta.width,height:meta.height};}catch{}catalog.push({...a,localPath:'reference/'+local,publicPath:'/reference-assets/'+local.slice(7),type:category,extension:ext,size:body.length,dimensions,highestResolutionIdentified:a.responsiveVariants.length? [...a.responsiveVariants,a.originalUrl].find(u=>!/-\d+x\d+\./.test(u))||a.originalUrl:a.originalUrl});}catch(e){catalog.push({...a,error:e.message});}if(catalog.length%25===0){console.log('Assets',catalog.length,'/',found.length);await write('assets.json',catalog);}}
 await write('assets.json',catalog);console.log('Downloaded',catalog.filter(a=>!a.error).length);
} else if(mode==='screenshots'){
 const pages=JSON.parse(await fs.readFile(path.join(root,'pages.json'),'utf8')).filter(p=>!p.error);const sizes={'desktop-large':[1920,1080],desktop:[1440,1000],tablet:[768,1024],mobile:[390,844]};
 for(const [name,[width,height]] of Object.entries(sizes)){await page.setViewportSize({width,height});for(const p of pages){const file=path.join(root,'screenshots',name,slug(p.url)+'.png');try{await fs.access(file);continue;}catch{}try{console.log(name,p.route);await page.goto(p.url,{waitUntil:'domcontentloaded',timeout:45000});await page.waitForTimeout(1000);await scroll(page);await fs.mkdir(path.dirname(file),{recursive:true});await page.screenshot({path:file,fullPage:true,timeout:45000});}catch(e){console.log('ERROR',e.message);}}}
} else if(mode==='states'){
 await fs.mkdir(path.join(root,'states'),{recursive:true});await page.goto(origin,{waitUntil:'networkidle'});await scroll(page);
 await page.screenshot({path:path.join(root,'states','navbar-default.png')});
 for(const name of ['Markets','Trading','Learn','About']){const nav=page.locator('header .elementor-nav-menu--main').getByText(name,{exact:true}).first();try{await nav.hover();await page.waitForTimeout(400);await page.screenshot({path:path.join(root,'states','menu-'+name.toLowerCase()+'.png')});}catch(e){console.log(e.message);}}
 const faq=page.locator('.elementor-tab-title').first();if(await faq.count()){await faq.scrollIntoViewIfNeeded();await page.screenshot({path:path.join(root,'states','faq-default.png')});await faq.click();await page.screenshot({path:path.join(root,'states','faq-toggled.png')});}
 await page.setViewportSize({width:390,height:844});await page.goto(origin,{waitUntil:'networkidle'});const menu=page.locator('.elementor-menu-toggle').filter({visible:true}).first();if(await menu.count()){await menu.click();await page.screenshot({path:path.join(root,'states','mobile-menu.png')});}
 console.log('States captured');
}
} finally {await browser.close();}
