'use client';
import {useRef,useState} from 'react';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {navigation} from '../data/site';
import {account,downloads} from '../lib/site';
import {Button,Container,Icon,Picture} from './ui';
function NavItems({mobile=false,onNavigate=()=>{}}){const [open,setOpen]=useState('');const current=usePathname();return <ul className={mobile?'mobile-nav':'desktop-nav'} onKeyDown={e=>{if(e.key==='Escape')setOpen('')}}>{navigation.map(group=><li key={group.label} onMouseEnter={()=>!mobile&&setOpen(group.label)} onMouseLeave={()=>!mobile&&setOpen('')} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setOpen('')}}>{group.href?<Link href={group.href} onClick={onNavigate} aria-current={current===group.href?'page':undefined}>{group.label}</Link>:<><button aria-expanded={open===group.label} aria-controls={`${mobile?'mobile':'desktop'}-${group.label}`} onClick={()=>setOpen(open===group.label?'':group.label)}>{group.label}<Icon name="down" size={13}/></button><ul id={`${mobile?'mobile':'desktop'}-${group.label}`} className={`dropdown ${open===group.label?'is-open':''}`}>{group.items.map(([name,route])=><li key={name}>{route?<Link href={`/${route}/`} onClick={onNavigate} aria-current={current===`/${route}/`?'page':undefined}>{name}</Link>:<span className="coming-soon">{name}<small>Coming Soon</small></span>}</li>)}</ul></>}</li>)}</ul>}
export default function Header(){const dialog=useRef(null);const close=()=>dialog.current?.close();return <>
<header className="site-header"><Container className="header-inner"><Link href="/" aria-label="TradeKaro home"><Picture name="orijnal.png" alt="TradeKaro" className="logo"/></Link><nav aria-label="Main navigation"><NavItems/></nav><div className="header-actions"><Button variant="black" href={account.login} arrow>Log in</Button><Button variant="white" arrow>Register Now</Button></div><button className="menu-trigger" aria-label="Open navigation" onClick={()=>dialog.current.showModal()}><Icon name="menu" size={30}/></button></Container></header>
<div className="mobile-account"><Link href={account.login}><Icon name="users" size={22}/>Sign In</Link><Link href={account.register}><Icon name="register" size={22}/>Register Now</Link></div>
<dialog className="mobile-drawer" ref={dialog} onClick={e=>{if(e.target===dialog.current)close()}}><div className="drawer-content"><button className="drawer-close" onClick={close} aria-label="Close navigation"><Icon name="close"/></button><Link href="/" onClick={close}><Picture name="orijnal.png" alt="TradeKaro" className="drawer-logo"/></Link><nav aria-label="Mobile navigation"><NavItems mobile onNavigate={close}/></nav><Button href={account.login} arrow>Login</Button><Button variant="black" arrow>Register Now</Button><SocialLinks/></div></dialog>
<aside className="platform-rail" aria-label="Trading applications"><Link href={downloads.android}><Picture name="public-icon-0.svg" alt=""/><span>ANDROID</span></Link><Link href={downloads.apple}><Picture name="public-icon-1.svg" alt=""/><span>IOS</span></Link><Link href={downloads.desktop}><Picture name="public-icon-2.svg" alt=""/><span>DESKTOP</span></Link></aside>
<div className="mobile-platforms"><Link href={downloads.android}><Picture name="appstore.png" alt=""/>Android</Link><Link href="/contact-us/" className="whatsapp"><Icon name="whatsapp" size={35}/><span className="sr-only">Contact us</span></Link><Link href={downloads.apple}><Picture name="iphone.png" alt=""/>Apple</Link></div><Link href="/contact-us/" className="floating-contact" aria-label="Contact our team"><Icon name="whatsapp" size={30}/></Link>
</>}
export function SocialLinks(){return <div className="social-links">{[['f','https://www.facebook.com/profile.php?id=61565404107447'],['▶','https://www.youtube.com/@tradekaro.official'],['◎','https://www.instagram.com/tradekaro.official'],['➤','https://t.me/+lSfagHNJOv1kMjdk']].map(([label,href],i)=><a key={label} href={href} aria-label={['Facebook','YouTube','Instagram','Telegram'][i]} target="_blank" rel="noreferrer">{label}</a>)}</div>}

