import Link from 'next/link';
import pages from '../data/pages.json';
import {markets,articles} from '../data/site';
import {asset,downloads} from '../lib/site';
import {Container,Button,Icon,Picture,SectionTitle,Divider,RichText} from './ui';
import {Accordion,Carousel,Counter,VideoButton} from './Interactive';
const home=pages['/'];
export function Hero(){return <section className="home-hero"><div className="hero-gradient"/><Container className="hero-grid"><div className="hero-copy"><h1>Zero Brokerage<br/>in <em>All Markets</em></h1><div className="hero-margins"><p>NSE &amp; MCX Futures <strong>500X Margin</strong></p><p>Comex &amp; Currency <strong>200X Margin</strong></p><p>OPTION Buying <strong>10X margin</strong></p></div><p className="hero-description">Explore the World of Financial Markets with TradeKaro<br/><strong>99% ON TIME Deposit &amp; Withdrawals</strong></p><Button><Icon name="arrow" size={20}/>SIGN UP</Button></div><div className="hero-visual" style={{backgroundImage:`url('${asset('vyaparfx-hero.png')}')`}}><VideoButton src={asset('3b116f6b-f247-4b7c-462b-23a6748fd586_custom.mp4')} poster={asset('vyaparfx-hero.png')}/></div></Container></section>}
export function Benefits(){return <section className="benefits"><Container>{[['coins','Brokerage','without Tax'],['chart','500X','Margin'],['gift','Referral','Bonus'],['headset','24/7','Support'],['shield','Regulated','Broker'],['globe','Indian','Markets'],['coins','500+','Products'],['clock','10Sec','To Register'],['users','RM','Available']].map(([icon,a,b],i)=><div key={a}><Picture name={`public-icon-${i+3}.svg`} alt=""/><h3>{a}<br/>{b}</h3></div>)}</Container></section>}
export function MarketShowcase(){return <section className="market-showcase"><Container><Divider/><SectionTitle>Trade All Exchanges in<br/>one Platform</SectionTitle><div className="market-rows">{markets.map((market,i)=><Link href={`/${market.slug}/`} key={market.slug} className={`market-row ${i%2?'market-reverse':''}`}><div className="market-pill"><h3 className={market.name.length>8?'small-title':''}>{market.name}</h3><ul>{market.items.map(text=><li key={text}><Icon size={16}/>{text}</li>)}</ul></div><Picture name={market.image} alt={`${market.name} markets`} className="market-art"/></Link>)}</div></Container></section>}
export function FeatureGrid({blocks=home.sections[5].blocks.filter(b=>b.type==='feature'),className=''}){return <div className={`feature-grid ${className}`}>{blocks.map((block,i)=><article className="feature-card" key={i}><Picture name={block.images[0]?.src} alt=""/><RichText html={block.html}/></article>)}</div>}
export function WhyChoose(){return <section className="why-choose" style={{backgroundImage:`url('${asset('Frame-1.-2png.png')}')`}}><Container><Divider reverse/><SectionTitle>Why<br/><em>Choose TradeKaro?</em></SectionTitle><FeatureGrid/></Container></section>}
export function Platform(){return <section className="platform-section"><Picture name="mobile.png.webp" alt="" className="platform-decoration"/><Container><SectionTitle>A Superior Trading Platform</SectionTitle><p>Access our platform from any location, at any time, on both desktop and mobile devices. Experience the power of ultra-low latency and lightning-fast trade execution.</p><h3>Download Now</h3><div className="download-buttons">{[['play','Google Play',downloads.android],['globe','App Store',downloads.apple],['desktop','Desktop',downloads.desktop],['globe','Web',downloads.web]].map(([icon,label,href])=><Button href={href} key={label}><Icon name={icon} size={20}/>{label}</Button>)}</div></Container></section>}
export function Stats(){return <section className="stats"><Container>{[['Brokerage saved',1000000,'₹'],['Happy Traders',150000,''],['Withdrawals Processed',5328987,'₹'],['Active Trades',930200,'']].map(([label,value,prefix])=><div key={label}><Counter value={Number(value)} prefix={String(prefix)}/><span>{label}</span></div>)}</Container></section>}
export function Influencers(){const sources=['3b116f6b-f247-4b7c-462b-23a6748fd586_custom.mp4',''];const cards=home.sections[8].blocks.find(b=>b.type==='ucaddon_card_carousel');const links=cards.links.filter(l=>l.url.includes('lightbox'));function video(i){try{const hash=decodeURIComponent(new URL(links[i].url).hash.slice(1));return asset(JSON.parse(Buffer.from(new URLSearchParams(hash).get('settings'),'base64').toString()).url)}catch{return asset(sources[0])}}return <section className="influencers grid-background"><Container><Divider/><SectionTitle>Our Influencers</SectionTitle><Carousel className="influencer-carousel" label="influencers">{[1,2,3,4].map((n,i)=><div className="influencer-card" key={n}><Picture name={`F-thumb${n}.png`} alt={`TradeKaro influencer video ${n}`}/><VideoButton src={video(i)} poster={asset(`F-thumb${n}.png`)}/></div>)}</Carousel></Container></section>}
export function Testimonials(){const raw=home.sections[9].blocks[1].html;const people=[['Amit Khanna','Pediatrician','jake.png'],['Jatin Kumar','Engineer','jatin.png'],['Yogesh Nikam','IT Professional','yogesh.png'],['Rakesh Purohit','Sales Professional','rakesh.png']];let remaining=raw;const quotes=people.map(([name,job,image])=>{const part=remaining.split(name+job);remaining=part.slice(1).join(name+job);return {name,job,image,quote:part[0].trim()}});return <section className="testimonials"><Container><SectionTitle>Testimonials</SectionTitle><Carousel label="testimonials" className="testimonial-carousel">{quotes.map(person=><figure key={person.name}><blockquote>{person.quote}</blockquote><figcaption><Picture name={person.image} alt={person.name}/><span>{person.name}<small>{person.job}</small></span></figcaption></figure>)}</Carousel></Container></section>}
export function FAQ({items=home.sections[11].blocks[0].items,homeLayout=false}){return <section className={`faq-section ${homeLayout?'home-faq':''}`} style={{backgroundImage:`url('${asset('BG-2-2.png')}')`}}><Container>{homeLayout?<div className="faq-heading"><div><SectionTitle>Frequently Asked<br/>Questions</SectionTitle><p>You’ve got questions, we’ve got answers.</p></div><Picture name="vyaparfx-hanging-mark.svg" alt=""/><div className="faq-more"><SectionTitle>More Questions?</SectionTitle><Button href="/contact-us/" variant="whatsapp"><Icon name="whatsapp" size={18}/>WHATSAPP US</Button></div></div>:<SectionTitle>Frequently Asked Questions</SectionTitle>}<Accordion items={items}/>{homeLayout&&<div className="faq-more-mobile"><h3>More Questions?</h3><Button href="/contact-us/" variant="whatsapp"><Icon name="whatsapp" size={18}/>WHATSAPP US</Button></div>}</Container></section>}
export function GuideCard({article}){return <article className="guide-card"><Link href={`/${article.slug}/`}><Picture name={article.image} alt={article.title}/></Link><div><h3><Link href={`/${article.slug}/`}>{article.title}</Link></h3><Link className="read-more" href={`/${article.slug}/`}>READ MORE</Link><time>{article.date}</time></div></article>}
export function Guides(){return <section className="guides grid-background"><Container><Divider/><SectionTitle>Quick Guides</SectionTitle><Carousel label="guides" className="guide-carousel">{articles.map(article=><GuideCard key={article.slug} article={article}/>)}</Carousel></Container></section>}
