'use client';
import {useId,useRef,useState,useEffect} from 'react';
import {Icon,RichText} from './ui';
// Solid circle with a plus/minus cut out, matching the reference toggle icon.
function ToggleIcon({open}){return <svg className="toggle-icon" width="16" height="16" viewBox="0 0 16 16" aria-hidden="true"><circle cx="8" cy="8" r="8" fill="currentColor"/><path d={open?'M4.5 8h7':'M4.5 8h7M8 4.5v7'} stroke="#fff" strokeWidth="2" strokeLinecap="round"/></svg>}
export function Accordion({items,className=''}){const [expanded,setExpanded]=useState({});const id=useId();return <div className={`accordion ${className}`}>{items.map((item,i)=><div key={i} className={`accordion-item ${expanded[i]?'expanded':''}`}><h3><button id={`${id}-button-${i}`} aria-expanded={!!expanded[i]} aria-controls={`${id}-panel-${i}`} onClick={()=>setExpanded({...expanded,[i]:!expanded[i]})}>{item.question}<ToggleIcon open={!!expanded[i]}/></button></h3><div id={`${id}-panel-${i}`} role="region" aria-labelledby={`${id}-button-${i}`} hidden={!expanded[i]}><RichText html={item.answer}/></div></div>)}</div>}
export function Carousel({children,className='',label='Carousel'}){const rail=useRef(null);function move(direction){const el=rail.current;if(!el)return;const max=el.scrollWidth-el.clientWidth;const next=el.scrollLeft+direction*(el.firstElementChild?.getBoundingClientRect().width+20||el.clientWidth);el.scrollTo({left:next>max+10?0:next< -10?max:next,behavior:'smooth'});}return <div className={`carousel ${className}`} role="region" aria-label={label}><div className="carousel-track" ref={rail}>{children}</div><button className="carousel-prev" onClick={()=>move(-1)} aria-label={`Previous ${label}`}><Icon name="chevron" size={18}/></button><button className="carousel-next" onClick={()=>move(1)} aria-label={`Next ${label}`}><Icon name="chevron" size={18}/></button></div>}
export function VideoButton({src,poster,children=null,className=''}){const dialog=useRef(null);const video=useRef(null);return <><button className={`video-trigger ${className}`} onClick={()=>{dialog.current.showModal();video.current?.play().catch(()=>{});}} aria-label="Play video">{children||<Icon name="play" size={50}/>}</button><dialog className="video-modal" ref={dialog} onClose={()=>video.current?.pause()} onClick={e=>{if(e.target===dialog.current)dialog.current.close();}}><button className="video-close" aria-label="Close video" onClick={()=>dialog.current.close()}><Icon name="close" size={32}/></button><video ref={video} controls preload="none" src={src} poster={poster}/></dialog></>}
export function Tabs({items}){const [active,setActive]=useState(0);const id=useId();return <div className="tabs"><div role="tablist" aria-label="Available instruments">{items.map((item,i)=><button key={i} id={`${id}-tab-${i}`} role="tab" aria-selected={active===i} aria-controls={`${id}-panel-${i}`} tabIndex={active===i?0:-1} onClick={()=>setActive(i)} onKeyDown={e=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?items.length-1:(i+(e.key==='ArrowRight'?1:-1)+items.length)%items.length;setActive(next);document.getElementById(`${id}-tab-${next}`)?.focus();}}}>{item.title}</button>)}</div>{items.map((item,i)=><div key={i} role="tabpanel" id={`${id}-panel-${i}`} aria-labelledby={`${id}-tab-${i}`} hidden={active!==i} tabIndex={0}><RichText html={item.html}/></div>)}</div>}
export function Counter({value,prefix=''}){const ref=useRef(null);const [number,setNumber]=useState(value);useEffect(()=>{let frame;if(ref.current.getBoundingClientRect().top<innerHeight||matchMedia('(prefers-reduced-motion: reduce)').matches)return;setNumber(0);const observer=new IntersectionObserver(([entry])=>{if(!entry.isIntersecting)return;observer.disconnect();if(matchMedia('(prefers-reduced-motion: reduce)').matches){setNumber(value);return;}let start;const update=t=>{start??=t;const progress=Math.min((t-start)/1600,1);setNumber(Math.round(value*progress));if(progress<1)frame=requestAnimationFrame(update)};frame=requestAnimationFrame(update);});observer.observe(ref.current);return()=>{observer.disconnect();cancelAnimationFrame(frame)};},[value]);return <strong ref={ref}>{prefix}{number.toLocaleString('en-US')}</strong>}
// Loads a TradingView embed the same way the reference site does: a script tag carrying JSON config.
// The embed script looks up its container after it loads, so nothing is removed on unmount.
export function TradingViewWidget({script,config}){const ref=useRef(null);useEffect(()=>{const host=ref.current;if(!host)return;host.replaceChildren();const widget=document.createElement('div');widget.className='tradingview-widget-container__widget';const tag=document.createElement('script');tag.src=`https://s3.tradingview.com/external-embedding/embed-widget-${script}.js`;tag.async=true;tag.text=JSON.stringify(config);host.append(widget,tag);},[script,config]);return <div className="tradingview-widget-container" ref={ref}/>}
