import {Container,Button,Picture,RichText,SectionTitle,Icon} from './ui';
import {account} from '../lib/site';
import {Accordion,Tabs,TradingViewWidget} from './Interactive';
import {marketWidgets} from '../data/site';
import {FAQ,FeatureGrid} from './HomeSections';
import {ContactStrip} from './Footer';
export function PageHero({section,className='',actions=true,center=false}){const [heading,...subheadings]=section.blocks.filter(b=>b.type==='heading');const texts=section.blocks.filter(b=>b.type==='text');const picture=section.blocks.find(b=>b.type==='image');const buttons=section.blocks.filter(b=>b.type==='button');return <section className={`page-hero ${center?'centered-hero':''} ${className}`}><Container className={picture?'page-hero-grid':''}><div><h1>{heading?.text}</h1>{texts.map((b,i)=><RichText key={i} html={b.html}/>)}{subheadings.map((b,i)=><h2 key={i} className="hero-subheading">{b.text}</h2>)}{actions&&buttons.length>0&&<div className="hero-actions">{buttons.map((b,i)=><Button key={i} variant={i?'yellow':'black'} href={/CONTACT/i.test(b.text)?'/contact-us/':/DEMO/i.test(b.text)?account.demo:/IB/i.test(b.text)?'#partner-form':account.register}><Icon name={i?'globe':'register'} size={16}/>{b.text}</Button>)}</div>}</div>{picture&&<Picture name={picture.images[0]?.src} alt={heading?.text} className="page-hero-art"/>}</Container></section>}
export function MarketPage({data,slug}){const [hero,why,instruments,faq]=data.sections;const whyImage=why.blocks.find(b=>b.type==='image');const whyFAQ=why.blocks.find(b=>b.type==='accordion');const isMargin=['national-stock-exchange','indian-commodity'].includes(slug);return <><PageHero section={hero} className={`market-hero ${isMargin?'':'tall-hero'}`}/><section className="market-why grid-background"><Container><SectionTitle>{why.headings[0].split('TradeKaro')[0]}<em>TradeKaro</em>?</SectionTitle><div className="market-why-grid"><Picture name={whyImage?.images[0]?.src} alt="Trading features illustrated"/><Accordion items={whyFAQ?.items||[]}/></div></Container></section><Instruments section={instruments} slug={slug}/><FAQ items={faq.blocks.find(b=>b.type==='accordion')?.items||[]}/><ContactStrip/></>}

// Mirrors the reference layout: instruments (optionally framed by connector arrows) beside a margin example or live widget.
function Instruments({section,slug}){const blocks=section.blocks;const tab=blocks.find(b=>b.type==='tabs');const mobileList=blocks.find(b=>b.type==='accordion');const table=blocks.find(b=>b.type==='html'&&b.html.includes('<table'));const connectors=blocks.some(b=>b.images[0]?.src.endsWith('arrowup.svg'));const marginStart=blocks.findIndex((b,i)=>i>0&&b.type==='heading');const margin=marginStart>0?blocks.slice(marginStart):[];const widget=marketWidgets[slug];const wide=slug==='national-stock-exchange';
 const list=tab?<><div className="instrument-tabs"><Tabs items={tab.tabs.map((t,i)=>({title:tab.tabTitles[i],html:t.html}))}/></div>{mobileList&&<div className="instrument-mobile"><Accordion items={mobileList.items}/></div>}</>:<RichText html={table?.html} className="instrument-table"/>;
 return <section className="instruments-section"><Container className={wide?'':'instruments-narrow'}><SectionTitle>{section.headings[0]}</SectionTitle><div className={`instruments-panel ${wide?'instruments-wide':''} ${connectors?'has-connectors':''}`}>
  <div className="instrument-list">{connectors&&<Picture name="arrowup.svg" alt="" className="connector connector-up"/>}{list}{connectors&&<Picture name="arrowdown.svg" alt="" className="connector connector-down"/>}</div>
  <div className="instrument-side">{margin.length>0?<MarginExample blocks={margin}/>:widget&&<div className="instrument-box widget-box"><TradingViewWidget script={widget.script} config={widget.config}/></div>}</div>
 </div></Container></section>}

// Headings arrive as "Label<br>Amount"; the amount is shown in the brand colour, as on the reference.
function MarginExample({blocks}){const [title,...rest]=blocks;return <><h3 className="margin-title">{title.text}</h3><div className="instrument-box margin-box">{rest.map((b,i)=>{if(b.type==='divider')return <hr key={i}/>;if(b.type==='text')return <p key={i} className="margin-note">{b.text}</p>;const [label,...amount]=b.text.split('\n').map(s=>s.trim()).filter(Boolean);const kind=i===0?'margin-case':/^With /.test(label)?'margin-ours':'margin-row';return <h4 key={i} className={kind}>{label}{amount.length>0&&<span>{amount.join(' ')}</span>}</h4>})}</div></>}

export function TradingPage({data}){const fee=data.sections.find(s=>s.headings[0]?.startsWith('Zero Deposit'));const margin=data.sections.find(s=>s.headings[0]?.startsWith('Margin required'));const faq=data.sections.at(-1);return <><PageHero section={data.sections[0]} center className="trading-hero"/><section className="trading-benefits grid-background"><Container><SectionTitle>{data.sections[1].headings[0]}</SectionTitle><FeatureGrid blocks={data.sections[1].blocks.filter(b=>b.type==='feature')} className="flat-features"/></Container></section>{margin&&<section className="margin-table-section grid-background"><Container><SectionTitle>{margin.headings[0]}</SectionTitle><p>{margin.headings[1]}</p><div className="margin-table"><RichText html={margin.blocks.find(b=>b.type==='html')?.html}/></div></Container></section>}<section className="zero-fees"><Container><Picture name={fee.blocks.find(b=>b.type==='image')?.images[0]?.src} alt="Zero charges"/><div><SectionTitle>{fee.headings[0]}</SectionTitle><RichText html={fee.blocks.find(b=>b.type==='text')?.html}/></div></Container></section><FAQ items={faq.blocks.find(b=>b.type==='accordion')?.items||[]}/><ContactStrip/></>}
