import {chromium} from 'playwright';
import fs from 'node:fs/promises';
import sharp from 'sharp';
const run=process.argv[2]||'pass-1';
const b=await chromium.launch({channel:'chrome'});
const p=await b.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));
await fs.mkdir(`reference/comparisons/${run}`,{recursive:true});
for(const [name,width,height] of [['desktop',1440,1000],['mobile',390,844],['tablet',768,1024],['desktop-large',1920,1080]]){
 await p.setViewportSize({width,height});await p.goto('http://127.0.0.1:3000/',{waitUntil:'networkidle'});await p.evaluate(()=>document.fonts.ready);await p.evaluate(async()=>{for(let y=0;y<document.body.scrollHeight;y+=700){scrollTo({top:y,behavior:"instant"});await new Promise(r=>setTimeout(r,70));}scrollTo({top:0,behavior:"instant"})});await p.waitForTimeout(1700);
 const local=`reference/comparisons/${run}/${name}-home.png`;await p.screenshot({path:local,fullPage:true});await p.screenshot({path:`reference/comparisons/${run}/${name}-hero.png`});const metrics=await p.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,height:document.body.scrollHeight,sections:[...document.querySelectorAll('main>section')].map(s=>({name:s.querySelector('h1,h2')?.textContent,y:Math.round(s.getBoundingClientRect().y),h:Math.round(s.getBoundingClientRect().height)})),missingImages:[...document.images].filter(i=>!i.complete||!i.naturalWidth).map(i=>i.src)}));await fs.writeFile(`reference/comparisons/${run}/${name}-metrics.json`,JSON.stringify(metrics,null,2));
 const baseline=`reference/comparisons/clean-reference/${name}-home.png`;try{await fs.access(baseline)}catch{await fs.mkdir('reference/comparisons/clean-reference',{recursive:true});await p.goto('https://tradekaro.com/',{waitUntil:'domcontentloaded'});await p.addStyleTag({content:'[class*="zsiq"],#zsiqchat{display:none!important}'});await p.waitForTimeout(1200);await p.evaluate(async()=>{for(let y=0;y<document.body.scrollHeight;y+=700){scrollTo({top:y,behavior:"instant"});await new Promise(r=>setTimeout(r,70));}scrollTo({top:0,behavior:"instant"})});await p.waitForTimeout(1700);await p.screenshot({path:baseline,fullPage:true});await p.screenshot({path:`reference/comparisons/clean-reference/${name}-hero.png`});}
 const [a,c]=await Promise.all([sharp(baseline).resize({width:480}).png().toBuffer({resolveWithObject:true}),sharp(local).resize({width:480}).png().toBuffer({resolveWithObject:true})]);await sharp({create:{width:960,height:Math.max(a.info.height,c.info.height),channels:4,background:'#dddddd'}}).composite([{input:a.data,left:0,top:0},{input:c.data,left:480,top:0}]).png().toFile(`reference/comparisons/${run}/${name}-side-by-side.png`);console.log(name,metrics.height,'overflow',metrics.scrollWidth-width,'missing',metrics.missingImages.length);
}await fs.writeFile(`reference/comparisons/${run}/errors.json`,JSON.stringify(errors,null,2));await b.close();
